### ISSUE TITLE
Pre-work

### ISSUE THREAD

**Issue by nongdenchet** [nongdenchet/the_ruby_blog#1]
Here is my Pre-work
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Rails submission, nongdenchet!

 :bow: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by harley** [comment]
Hi @nongdenchet, :+1: thanks for giving this a try even though you didn't have much time. Some cool things:
- Custom heroku app name. Nice and clean UI
- User authentication with Devise. Good thought to customize Devise to use DELETE for logout
- Nice gems used for the project. The code handling flash messages is well done and toastr is cool
- Nice use of `configure_permitted_parameters` to allow permit updating more fields in Devise
- Validations in Article model
- Use of partials for collection `@articles`

:thought_balloon: A couple of areas to improve:
- Some required user stories are not yet completed. Are you able to find some time to improve that?
- Markdown support: this is important. Can you add this in?

Overall, this app has potential but we'd like to see some more effort put into it: the required user stories should be completed. Naturally, after your great submissions for Android, we have high expectations of you ;-) Let us know if you have any questions and we are here to help! Feel to email ruby at coderschool dot vn. or ping me on messenger for any questions.

**Comment by nongdenchet** [comment]
@harley, Yes I will improve the user stories and add markdown support

**Comment by nongdenchet** [comment]
@harley, I have finished user stories and markdown support

**Comment by harley** [comment]
Hi @nongdenchet -- glad to see the updates. Nice work adding markdown and completing the required stories. Some questions:
- Why do you use a text area instead of a text field for search?
- If I search with empty text, shouldn't I get all posts? How would you fix that?
- Can you make the search case insensitive?

We have a lot of good submissions with the optional stories completed. Your submission is pretty good but you haven't tried optional stories. I'd like you to see you complete at least one optional story if you can. Let me know if you have any questions along the way :)

**Comment by nongdenchet** [comment]
@harley, I have added some optional feature (view counts, comment). I have also fixed some bugs you mentioned
